import torch
import argparse
import numpy as np
import os
from pi3.utils.basic import load_multimodal_data, write_ply
from pi3.utils.geometry import depth_edge, recover_intrinsic_from_rays_d
from pi3.models.pi3x import Pi3X

def voxel_downsample(points, colors, voxel_size):
    """
    Groups points into a 3D grid (voxels) and keeps only one point per voxel.
    This effectively eliminates duplicate points generated by overlapping camera views.
    """
    if voxel_size <= 0.0:
        return points, colors
        
    # Move to CPU numpy for easier indexing
    points_np = points.cpu().numpy()
    colors_np = colors.cpu().numpy()
    
    # Quantize spatial coordinates to create a grid of voxels
    voxel_coords = np.round(points_np / voxel_size).astype(np.int32)
    
    # Find the unique voxels and get the index of the first point that falls into each
    _, unique_indices = np.unique(voxel_coords, axis=0, return_index=True)
    
    # Slice the original arrays to keep only the unique points
    downsampled_points = torch.from_numpy(points_np[unique_indices]).to(points.device)
    downsampled_colors = torch.from_numpy(colors_np[unique_indices]).to(colors.device)
    
    return downsampled_points, downsampled_colors

if __name__ == '__main__':
    # --- Argument Parsing ---
    parser = argparse.ArgumentParser(description="Run inference with the Pi3 model.")
    
    parser.add_argument("--data_path", type=str, default='examples/skating.mp4',
                        help="Path to the input image directory or a video file.")
    
    parser.add_argument("--conditions_path", type=str, default=None,
                        help="Optional path to a .npz file containing 'poses', 'depths', 'intrinsics'.")

    parser.add_argument("--save_path", type=str, default='examples/result.ply',
                        help="Path to save the output .ply file.")
    parser.add_argument("--interval", type=int, default=-1,
                        help="Interval to sample image. Default: 1 for images dir, 10 for video. Increase to compute faster.")
    parser.add_argument("--ckpt", type=str, default=None,
                        help="Path to the model checkpoint file. Default: None")
    parser.add_argument("--device", type=str, default='cuda',
                        help="Device to run inference on ('cuda' or 'cpu'). Default: 'cuda'")
                        
    # --- NEW OPTIMIZATION ARGUMENTS ---
    parser.add_argument("--voxel_size", type=float, default=0.03,
                        help="Size of the voxel grid (in meters) to merge overlaps. Larger = smaller file size. Set to 0 to disable.")
    parser.add_argument("--conf_thresh", type=float, default=0.5,
                        help="Confidence threshold (0.0 to 1.0). Default was 0.1. Higher = cleaner, smaller point cloud.")
                        
    args = parser.parse_args()
    if args.interval < 0:
        args.interval = 10 if args.data_path.endswith('.mp4') else 1
    print(f'Sampling interval: {args.interval}')

    # 1. Prepare input data
    device = torch.device(args.device)

    # Load optional conditions from .npz
    poses = None
    depths = None
    intrinsics = None

    if args.conditions_path is not None and os.path.exists(args.conditions_path):
        print(f"Loading conditions from {args.conditions_path}...")
        data_npz = np.load(args.conditions_path, allow_pickle=True)

        poses = data_npz['poses']             # Expected (N, 4, 4) OpenCV camera-to-world
        depths = data_npz['depths']           # Expected (N, H, W)
        intrinsics = data_npz['intrinsics']   # Expected (N, 3, 3)

    conditions = dict(
        intrinsics=intrinsics,
        poses=poses,
        depths=depths
    )

    # Load images (Required)
    imgs, conditions = load_multimodal_data(args.data_path, conditions, interval=args.interval, device=device) 
    use_multimodal = any(v is not None for v in conditions.values())
    if not use_multimodal:
        print("No multimodal conditions found. Disable multimodal branch to reduce memory usage.")

    # 2. Prepare model
    print(f"Loading model...")
    if args.ckpt is not None:
        model = Pi3X(use_multimodal=use_multimodal).eval()
        if args.ckpt.endswith('.safetensors'):
            from safetensors.torch import load_file
            weight = load_file(args.ckpt)
        else:
            weight = torch.load(args.ckpt, map_location=device, weights_only=False)
        
        model.load_state_dict(weight, strict=False)
    else:
        model = Pi3X.from_pretrained("yyfz233/Pi3X").eval()
        # or download checkpoints from `https://huggingface.co/yyfz233/Pi3X/resolve/main/model.safetensors`, and `--ckpt ckpts/model.safetensors`
        if not use_multimodal:
            model.disable_multimodal()
    model = model.to(device)

    # 3. Infer
    print("Running model inference...")
    dtype = torch.bfloat16 if torch.cuda.get_device_capability()[0] >= 8 else torch.float16
    
    with torch.no_grad():
        with torch.amp.autocast('cuda', dtype=dtype):
            res = model(
                imgs=imgs, 
                **conditions
            )

    # 3.5 Recover intrinsic from rays_d
    rays_d = torch.nn.functional.normalize(res['local_points'], dim=-1)
    K = recover_intrinsic_from_rays_d(rays_d, force_center_principal_point=True)
    print(f"Recovered first frame intrinsic: \n{K[0, 0].cpu().numpy()}")
    if conditions['intrinsics'] is not None:
        print(f"Original first frame intrinsic: \n{conditions['intrinsics'][0, 0].cpu().numpy()}")

    # 4. process mask
    # UPDATED: Use user-defined confidence threshold instead of hardcoded 0.1
    masks = torch.sigmoid(res['conf'][..., 0]) > args.conf_thresh
    non_edge = ~depth_edge(res['local_points'][..., 2], rtol=0.03)
    masks = torch.logical_and(masks, non_edge)[0]

    # Extract all points before downsampling
    raw_points = res['points'][0][masks]
    raw_colors = imgs[0].permute(0, 2, 3, 1)[masks]
    
    print(f"Total points generated before overlap removal: {raw_points.shape[0]}")

    # 5. Remove Overlaps (Voxel Downsample)
    final_points, final_colors = voxel_downsample(raw_points, raw_colors, args.voxel_size)
    print(f"Total points after removing camera overlaps: {final_points.shape[0]}")

    # 6. Save points
    print(f"Saving point cloud to: {args.save_path}")
    if os.path.dirname(args.save_path):
        os.makedirs(os.path.dirname(args.save_path), exist_ok=True)
        
    write_ply(final_points.cpu(), final_colors.cpu(), args.save_path)
    print("Done.")
